baseURL = "https://allixender.github.io/30daymaps2021/"
languageCode = "en-us"
title = "#DayMapChallenge 2021"
theme = "mediumish-gohugo-theme"
summaryLength = 0
copyright = "2021 Alexander Kmoch CC-SA-BY 4.0"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="map maps maps"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Alexander Kmoch"
  thumbnail = "/images/alex_hat.jpg"
  description = "Geoinformatics, Tartu, Estonia."

[params.index]
  picture = "/images/30dmpc_2021.png"
  title = "I try making some maps again..."
  subtitle = ""
  mdtext = '''
### This is my repo for [maps](./maps)

[tjukanovt/30DayMapChallenge](https://github.com/tjukanovt/30DayMapChallenge)

'''
  alertbar = false

[params.social]
  github = "allixender"
  linkedin = "allixender"
  twitter = "allixender"

## Main Menu
[[menu.main]]
    name = "Maps"
    weight = 100
    identifier = "maps"
    url = "/maps"
[[menu.main]]
    name = "About this page"
    identifier = "about"
    weight = 200
    url = "/"
